### PR TITLE
Serialization for ptrs to TR and tests

### PR DESCRIPTION
**Pull request by jmcarcell**
I have not run the tests but it runs fine in DQM

### CODE REVIEW

**Comment by eflumerf** [comment]
I'm the author, so probably not the best reviewer ;)

**Review by mroda88 — APPROVED** [review]
Code looks ok to me and the unittests were successful on np04 machine. Should I try a specific run? From the previous comments, I think that was done by Juan, I think.

**Comment by jmcarcell** [comment]
Don't worry, I'm running it with the DQM - DF connection on, that is the only place where this is used and it works fine, no crashes so far.

**Comment by mroda88** [comment]
@eflumerf I think you can merge

**Pull request merged**
